
  CREATE TABLE "JDBC"."LAYERED_EMPLOYEE" 
   (	"ENO" NUMBER(10,0) NOT NULL ENABLE, 
	"ENAME" VARCHAR2(20 BYTE), 
	"EADD" VARCHAR2(20 BYTE), 
	"SALARY" FLOAT(120), 
	"GROSSSALARY" FLOAT(120), 
	"NETSALARY" FLOAT(126), 
	 CONSTRAINT "LAYERED_EMPLOYEE_PK" PRIMARY KEY ("ENO")

   CREATE SEQUENCE  "JDBC"."ENO_SEQ"  MINVALUE 100 MAXVALUE 1000 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
