 CREATE TABLE "JDBC"."COOKIE_PERSON" 
   (	"PID" NUMBER NOT NULL ENABLE, 
	"PNAME" VARCHAR2(20 BYTE), 
	"FNAME" VARCHAR2(20 BYTE), 
	"AGE" NUMBER, 
	"INCOME" NUMBER, 
	"TAX" NUMBER, 
	 CONSTRAINT "COOKIE_PERSON_PK" PRIMARY KEY ("PID")
	 
   CREATE SEQUENCE  "JDBC"."PID_SEQ"  MINVALUE 1 MAXVALUE 1000 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
