
  CREATE TABLE "JDBC"."JOBSEEKER_INFO" 
   (	"JSID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(20 BYTE), 
	"ADDR" VARCHAR2(20 BYTE), 
	"AGE" NUMBER(5,0), 
	"EXPERIENCE" NUMBER, 
	"SKILLS" VARCHAR2(20 BYTE), 
	"CITY" VARCHAR2(20 BYTE), 
	"SALARY" NUMBER, 
	 CONSTRAINT "JOBSEEKER_INFO_PK" PRIMARY KEY ("JSID")

	 
   CREATE SEQUENCE  "JDBC"."JSID_SEQ"  MINVALUE 100 MAXVALUE 1000 INCREMENT BY 1 START WITH 100 CACHE 20 NOORDER  NOCYCLE ;
